TIPO_DOCUMENTO_DNI = '03'
TIPO_DOCUMENTO_CE = '06'
TIPO_DOCUMENTO_CPP = '26'
# TIPO_DOCUMENTO_PTP = '18'

TIPO_CONTRI_PERSONA_NATURAL_C = '01'
TIPO_CONTRI_EIRL = '07'
TIPO_CONTRI_SA = '26'
TIPO_CONTRI_SA_A = '38'
TIPO_CONTRI_SA_C = '39'



